# Generated by Django 5.1.7 on 2025-03-27 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, editable=False, verbose_name='Fecha de Inicio')),
                ('duration', models.PositiveSmallIntegerField(default=1, verbose_name='duración en días')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('pack_cost', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='costo unitario de pack')),
                ('balances_created', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
            },
        ),
    ]
