# Generated by Django 5.0.6 on 2024-10-23 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Inicio')),
                ('duration', models.PositiveSmallIntegerField(default=1, verbose_name='duración en días')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de finalización')),
                ('envelope_cost', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='costo unitario de sobre')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
            },
        ),
    ]
