# Generated by Django 5.0.6 on 2024-10-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tema de la colección')),
                ('image', models.ImageField(null=True, upload_to='albums')),
            ],
            options={
                'verbose_name': 'colección',
                'verbose_name_plural': 'Collectiones',
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.BigIntegerField(verbose_name='Número de página')),
                ('slot', models.BigIntegerField(verbose_name='Número de barajita')),
                ('ordinal', models.BigIntegerField(default=0, verbose_name='number ordinal por página')),
                ('number', models.BigIntegerField(default=0, verbose_name='Número en album')),
                ('rarity_factor', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Factor de rareza')),
                ('Collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coordinates', to='promotions.collection')),
            ],
            options={
                'verbose_name_plural': 'Coordinates',
            },
        ),
        migrations.CreateModel(
            name='StandardPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('Collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premios_standard', to='promotions.collection')),
            ],
            options={
                'verbose_name_plural': 'premios standard',
            },
        ),
        migrations.CreateModel(
            name='SurprisePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('Collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surprise_prizes', to='promotions.collection')),
            ],
            options={
                'verbose_name': 'premio_sorpresa',
                'verbose_name_plural': 'premios sorpresa',
            },
        ),
    ]
