# Generated by Django 5.0.6 on 2024-12-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='balances_created',
            field=models.BooleanField(default=False),
        ),
    ]
