# Generated by Django 5.0.6 on 2024-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de finalización'),
        ),
    ]
