# Generated by Django 5.0.6 on 2024-10-25 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_collection_coordinate_standardprize_surpriseprize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='Collection',
        ),
        migrations.AlterField(
            model_name='standardprize',
            name='Collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_prizes', to='promotions.collection'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='promotions.collection'),
            preserve_default=False,
        ),
    ]
