# Generated by Django 5.0.6 on 2024-12-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion_balances_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='balances_created',
            field=models.BooleanField(),
        ),
    ]
