# Generated by Django 5.0.6 on 2024-10-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_remove_coordinate_collection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'colección', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.RenameField(
            model_name='standardprize',
            old_name='Collection',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='surpriseprize',
            old_name='Collection',
            new_name='collection',
        ),
    ]
