# Generated by Django 5.0.6 on 2024-10-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surpriseprize',
            old_name='number',
            new_name='page',
        ),
    ]
