# Generated by Django 5.0.6 on 2025-01-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_promotion_balances_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de finalización'),
        ),
    ]
