# Generated by Django 5.0.6 on 2024-10-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_rename_number_surpriseprize_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surpriseprize',
            name='page',
        ),
        migrations.AddField(
            model_name='surpriseprize',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
