# Generated by Django 5.0.6 on 2025-01-10 12:13

import promotions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default=promotions.models.get_default_date, editable=False, verbose_name='Fecha de Inicio'),
        ),
    ]
