# Generated by Django 5.0.6 on 2024-10-27 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_remove_surpriseprize_page_surpriseprize_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='standardprize',
            options={'verbose_name_plural': 'prizes standard'},
        ),
        migrations.AlterModelOptions(
            name='surpriseprize',
            options={'verbose_name': 'prize_sorpresa', 'verbose_name_plural': 'prizes sorpresa'},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='envelope_cost',
        ),
        migrations.AddField(
            model_name='promotion',
            name='pack_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='costo unitario de pack'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='rarity_factor',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Factor de rarity'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='slot',
            field=models.BigIntegerField(verbose_name='Número de sticker'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(verbose_name='Date de finalización'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de Inicio'),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.BigIntegerField(default=1)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.collection')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.BigIntegerField(default=0, verbose_name='ordinal_box')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='promotions.edition')),
            ],
            options={
                'verbose_name_plural': 'boxes',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='promotions.edition')),
            ],
            options={
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='promotions.album')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.SmallIntegerField()),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='promotions.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.BigIntegerField(default=0, verbose_name='pack_ordinal')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='promotions.box')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='promotions.sale')),
            ],
        ),
        migrations.CreateModel(
            name='StandardAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.page')),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.standardprize')),
            ],
            options={
                'verbose_name_plural': 'premiaciones standard',
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(verbose_name='Number ordinal de sticker')),
                ('on_the_board', models.BooleanField(default=False)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='promotions.album')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to=settings.AUTH_USER_MODEL)),
                ('coordinate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='promotions.coordinate')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='promotions.pack')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('absolut_number', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='promotions.page')),
                ('sticker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.sticker')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
