# Generated by Django 5.0.6 on 2024-10-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_alter_collection_options_alter_standardprize_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardprize',
            options={'verbose_name_plural': 'standard prizes'},
        ),
        migrations.AlterModelOptions(
            name='surpriseprize',
            options={'verbose_name': 'surprise prize', 'verbose_name_plural': 'surprise prizes'},
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='rarity_factor',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Factor de rareza'),
        ),
    ]
