# Generated by Django 5.0.6 on 2025-01-13 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_update_promotions_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Fecha de Inicio'),
        ),
    ]
