# Generated by Django 5.0.6 on 2024-10-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_alter_standardprize_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandardAward',
            new_name='PagePrize',
        ),
        migrations.AlterModelOptions(
            name='pageprize',
            options={'verbose_name_plural': 'page prizes'},
        ),
    ]
