# Generated by Django 5.0.6 on 2024-10-31 17:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_rename_standardaward_pageprize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='circulation',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=20),
        ),
    ]
