# Generated by Django 5.0.6 on 2024-11-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseprofile')),
                ('rescue_options', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=('users.baseprofile',),
        ),
    ]
