# Generated by Django 5.0.6 on 2025-02-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collector',
            old_name='rescue_options',
            new_name='rescue_tickets',
        ),
    ]
