# Generated by Django 5.0.6 on 2024-08-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_useraccount_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
