# Generated by Django 5.0.6 on 2024-09-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_regionalmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionalManager',
        ),
    ]
