# Generated by Django 5.0.6 on 2024-09-23 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_regionalmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('first_last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[
                 ('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalManager',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='users.baseprofile')),
                ('email', models.EmailField(max_length=254,
                 unique=True, verbose_name='Email field')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('users.baseprofile',),
        ),
    ]
