# Generated by Django 5.0.6 on 2024-09-27 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_regionalmanager_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseprofile',
            old_name='first_last_name',
            new_name='last_name',
        ),
    ]
