# Generated by Django 5.0.6 on 2024-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_first_last_name_baseprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_collector',
            field=models.BooleanField(default=False),
        ),
    ]
