# Generated by Django 5.0.6 on 2024-09-30 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_useraccount_is_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalmanager',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regionalmanagers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LocalManager',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_localmanagers', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('users.baseprofile',),
        ),
    ]
