# Generated by Django 5.0.6 on 2024-10-02 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_regionalmanager_created_by_localmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sponsors', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('users.baseprofile',),
        ),
    ]
