# Generated by Django 5.0.6 on 2024-11-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tema de la colección')),
                ('image', models.ImageField(null=True, upload_to='albums')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.BigIntegerField(verbose_name='Número de página')),
                ('slot', models.BigIntegerField(verbose_name='Número de sticker')),
                ('ordinal', models.BigIntegerField(default=0, verbose_name='number ordinal por página')),
                ('number', models.BigIntegerField(default=0, verbose_name='Número en album')),
                ('rarity_factor', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Factor de rareza')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='sticker_collections.collection')),
            ],
            options={
                'verbose_name_plural': 'Coordinates',
            },
        ),
        migrations.CreateModel(
            name='StandardPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_prizes', to='sticker_collections.collection')),
            ],
            options={
                'verbose_name_plural': 'standard prizes',
            },
        ),
        migrations.CreateModel(
            name='SurprisePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surprise_prizes', to='sticker_collections.collection')),
            ],
            options={
                'verbose_name': 'surprise prize',
                'verbose_name_plural': 'surprise prizes',
            },
        ),
    ]
