# Generated by Django 5.0.6 on 2024-11-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='number',
            field=models.BigIntegerField(default=0, verbose_name='Número absoluto'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='ordinal',
            field=models.BigIntegerField(default=0, verbose_name='Ordinal'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='page',
            field=models.BigIntegerField(verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='slot',
            field=models.BigIntegerField(verbose_name='Casilla'),
        ),
    ]
