# Generated by Django 5.0.6 on 2024-11-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_collections', '0002_alter_coordinate_number_alter_coordinate_ordinal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='number',
            new_name='absolute_number',
        ),
        migrations.RenameField(
            model_name='coordinate',
            old_name='slot',
            new_name='slot_number',
        ),
    ]
