# Generated by Django 5.1.7 on 2025-03-11 12:32

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_manager', '0001_initial'),
        ('editions', '0001_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_date', models.DateField()),
                ('bank', models.CharField(choices=[('0102', 'Banco de Venezuela'), ('0104', 'Venezolano de Crédito'), ('0105', 'Banco Mercantil'), ('0108', 'BBVA Provincial'), ('0114', 'Bancaribe'), ('0115', 'Banco Exterior'), ('0116', 'Banco Occidental de Descuento'), ('0128', 'Banco Caroní'), ('0134', 'Banesco'), ('0137', 'Banco Sofitasa'), ('0138', 'Banco Plaza'), ('0146', 'Bangente'), ('0151', 'BFC Banco Fondo Común'), ('0156', '100% Banco'), ('0157', 'DelSur'), ('0163', 'Banco del Tesoro'), ('0166', 'Banco Agrícola de Venezuela'), ('0168', 'Bancrecer'), ('0169', 'Mi Banco'), ('0171', 'Banco Activo'), ('0172', 'Bancamiga'), ('0174', 'Banplus'), ('0175', 'Banco Bicentenario'), ('0177', 'Banfanb'), ('0178', 'N58 Banco Digital'), ('0191', 'Banco Nacional de Crédito')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(error_messages={'unique': 'La referencia del pago ya existe'}, max_length=20, unique=True)),
                ('id_number', models.CharField(help_text='Cédula del titular de la cuenta (sin letra inicial, guiones ni puntos)', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'Ingrese un número de cédula válido (6 hasta 8 dígitos)')])),
                ('capture', models.ImageField(upload_to='captures/payments', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Solo se permiten archivos de imagen (jpg, jpeg, png)')])),
                ('payment_type', models.CharField(choices=[('bank', 'Transferencia Bancaria'), ('mobile', 'Pago Móvil')], default='bank', max_length=6)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commerce.payment')),
                ('phone_code', models.CharField(choices=[('0412', '0412'), ('0414', '0414'), ('0416', '0416'), ('0424', '0424'), ('0426', '0426')], max_length=4)),
                ('phone_number', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Ingrese un número de teléfono válido (7 dígitos)')])),
            ],
            bases=('commerce.payment',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pack_cost', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='costo unitario del sobre')),
                ('box', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.box')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='collection_manager.collection')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='collection_manager.collection')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='editions.pack')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='commerce.sale')),
            ],
        ),
        migrations.CreateModel(
            name='DealerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='promotions.promotion')),
            ],
            options={
                'unique_together': {('dealer', 'promotion')},
            },
        ),
    ]
