# Generated by Django 5.0.6 on 2024-11-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.edition'),
        ),
    ]
