# Generated by Django 5.0.6 on 2024-11-26 20:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_edition'),
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='box',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.box'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
