# Generated by Django 5.0.6 on 2024-12-06 14:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_order_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_date', models.DateField()),
                ('bank', models.CharField(choices=[('0102', 'Banco de Venezuela'), ('0104', 'Venezolano de Crédito'), ('0105', 'Banco Mercantil'), ('0108', 'BBVA Provincial'), ('0114', 'Bancaribe'), ('0115', 'Banco Exterior'), ('0116', 'Banco Occidental de Descuento'), ('0128', 'Banco Caroní'), ('0134', 'Banesco'), ('0137', 'Banco Sofitasa'), ('0138', 'Banco Plaza'), ('0146', 'Bangente'), ('0151', 'BFC Banco Fondo Común'), ('0156', '100% Banco'), ('0157', 'DelSur'), ('0163', 'Banco del Tesoro'), ('0166', 'Banco Agrícola de Venezuela'), ('0168', 'Bancrecer'), ('0169', 'Mi Banco'), ('0171', 'Banco Activo'), ('0172', 'Bancamiga'), ('0174', 'Banplus'), ('0175', 'Banco Bicentenario'), ('0177', 'Banfanb'), ('0178', 'N58 Banco Digital'), ('0191', 'Banco Nacional de Crédito')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('id_number', models.CharField(help_text='Cédula del titular de la cuenta (sin letra inicial, guiones ni puntos)', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'Ingrese un número de cédula válido (6 hasta 8 dígitos)')])),
                ('capture', models.ImageField(upload_to='captures/payments')),
                ('payment_type', models.CharField(choices=[('bank', 'Transferencia Bancaria'), ('mobile', 'Pago Móvil')], default='bank', max_length=6)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commerce.payment')),
                ('phone_code', models.CharField(choices=[('0412', '0412'), ('0414', '0414'), ('0416', '0416'), ('0424', '0424'), ('0426', '0426')], max_length=4)),
                ('phone_number', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Ingrese un número de teléfono válido (7 dígitos)')])),
            ],
            bases=('commerce.payment',),
        ),
    ]
