# Generated by Django 5.0.6 on 2024-12-06 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_payment_mobilepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='capture',
            field=models.ImageField(upload_to='captures/payments', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Solo se permiten archivos de imagen (jpg, jpeg, png)')]),
        ),
    ]
