# Generated by Django 5.0.6 on 2024-12-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_payment_capture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(error_messages={'unique': 'Esta referencia ya existe.'}, max_length=20, unique=True),
        ),
    ]
