# Generated by Django 5.0.6 on 2024-12-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_alter_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(error_messages={'unique': 'La referencia del pago ya existe'}, max_length=20, unique=True),
        ),
    ]
