# Generated by Django 5.0.6 on 2024-12-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_dealerbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerbalance',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
