# Generated by Django 5.0.6 on 2024-12-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_dealerbalance_promotion'),
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='box',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='editions.box'),
        ),
    ]
