# Generated by Django 5.0.6 on 2024-12-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_alter_order_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerbalance',
            name='start_date',
            field=models.DateField(),
        ),
    ]
