# Generated by Django 5.0.6 on 2025-01-13 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_alter_dealerbalance_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
