# Generated by Django 5.0.6 on 2025-03-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0013_alter_collection_layout_alter_collection_promotion_and_more'),
        ('commerce', '0020_alter_sale_collector_alter_sale_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='collection_manager.collection'),
            preserve_default=False,
        ),
    ]
