# Generated by Django 5.0.6 on 2025-03-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_order_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='edition',
        ),
    ]
