# Generated by Django 5.0.6 on 2025-03-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0013_alter_collection_layout_alter_collection_promotion_and_more'),
        ('commerce', '0022_remove_order_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='collection_manager.collection'),
            preserve_default=False,
        ),
    ]
