# Generated by Django 5.0.6 on 2025-03-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_sale_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='edition',
        ),
    ]
