# Generated by Django 5.0.6 on 2024-11-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('editions', '0001_initial'),
        ('sticker_collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='editions.edition'),
        ),
        migrations.AddField(
            model_name='page',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='albums.album'),
        ),
        migrations.AddField(
            model_name='pageprize',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.page'),
        ),
        migrations.AddField(
            model_name='pageprize',
            name='prize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sticker_collections.standardprize'),
        ),
        migrations.AddField(
            model_name='slot',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='albums.page'),
        ),
        migrations.AddField(
            model_name='slot',
            name='sticker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.sticker'),
        ),
    ]
