# Generated by Django 5.0.6 on 2024-11-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='absolut_number',
            new_name='absolute_number',
        ),
    ]
