# Generated by Django 5.0.6 on 2024-11-15 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_initial'),
        ('editions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('collector', 'edition')},
        ),
    ]
