# Generated by Django 5.0.6 on 2024-11-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
