# Generated by Django 5.0.6 on 2025-01-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_slot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='prize_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
