# Generated by Django 5.0.6 on 2025-01-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_page_prize_claimed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='prize_claimed',
        ),
    ]
