# Generated by Django 5.0.6 on 2025-02-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_pageprize_claimed_by_pageprize_claimed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageprize',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_prize', to='albums.page'),
        ),
    ]
