# Generated by Django 5.0.6 on 2025-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_alter_pageprize_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageprize',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pageprize',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'No reclamado'), (2, 'Reclamado'), (3, 'En tránsito'), (4, 'Entregado')], default=1),
        ),
    ]
