# Generated by Django 5.0.6 on 2025-02-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_pageprize_claimed_pageprize_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageprize',
            name='claimed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
