# Generated by Django 5.0.6 on 2025-03-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_pageprize_claimed_date'),
        ('collection_manager', '0013_alter_collection_layout_alter_collection_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='collection_manager.collection'),
        ),
    ]
