# Generated by Django 5.0.6 on 2025-03-06 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_album_collection'),
        ('collection_manager', '0013_alter_collection_layout_alter_collection_promotion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('collector', 'collection')},
        ),
    ]
