# Generated by Django 5.0.6 on 2025-03-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_alter_album_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='edition',
        ),
    ]
