# Generated by Django 5.0.6 on 2025-03-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_remove_album_edition'),
        ('collection_manager', '0013_alter_collection_layout_alter_collection_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='collection_manager.collection'),
            preserve_default=False,
        ),
    ]
