# Generated by Django 5.1.7 on 2025-03-11 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='images/themes/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='promotions.promotion')),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='collection_manager.layout')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='collection_manager.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.BigIntegerField(verbose_name='Página')),
                ('slot_number', models.BigIntegerField(verbose_name='Casilla')),
                ('absolute_number', models.BigIntegerField(default=0, verbose_name='Número absoluto')),
                ('ordinal', models.BigIntegerField(default=0, verbose_name='Ordinal')),
                ('rarity_factor', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Factor de rareza')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/coordinates/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='collection_manager.collection')),
            ],
            options={
                'verbose_name_plural': 'Coordinates',
            },
        ),
        migrations.CreateModel(
            name='StandardPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('description', models.CharField(default='undefined', max_length=100)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_prizes', to='collection_manager.collection')),
            ],
            options={
                'verbose_name_plural': 'standard prizes',
            },
        ),
        migrations.CreateModel(
            name='SurprisePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=0)),
                ('description', models.CharField(default='undefined', max_length=100)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surprise_prizes', to='collection_manager.collection')),
            ],
            options={
                'verbose_name': 'surprise prize',
                'verbose_name_plural': 'surprise prizes',
            },
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('theme', 'promotion'), name='unique_collection'),
        ),
    ]
