# Generated by Django 5.1.7 on 2025-03-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTemplate',
            fields=[
                ('theme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collection_manager.theme')),
                ('layout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='album', to='collection_manager.layout')),
            ],
            bases=('collection_manager.theme',),
        ),
    ]
