# Generated by Django 5.0.6 on 2024-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0002_alter_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(upload_to='images/collections/'),
        ),
    ]
