# Generated by Django 5.1.7 on 2025-03-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0002_albumtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='collection_manager.albumtemplate'),
            preserve_default=False,
        ),
    ]
