# Generated by Django 5.1.7 on 2025-03-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0003_coordinate_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='collection',
        ),
    ]
