# Generated by Django 5.0.6 on 2024-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0003_alter_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/coordinates/'),
        ),
    ]
