# Generated by Django 5.1.7 on 2025-03-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0004_remove_coordinate_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='album_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='collection_manager.albumtemplate'),
            preserve_default=False,
        ),
    ]
