# Generated by Django 5.1.7 on 2025-03-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0005_collection_album_template'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_collection',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='theme',
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('album_template', 'promotion'), name='unique_collection'),
        ),
    ]
