# Generated by Django 5.0.6 on 2025-03-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0005_theme'),
        ('editions', '0009_edition_editions_ed_promoti_bce6b3_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='OldCollection',
        ),
    ]
