# Generated by Django 5.1.7 on 2025-03-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0006_remove_collection_unique_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='album_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='collection_manager.albumtemplate'),
        ),
    ]
