# Generated by Django 5.0.6 on 2025-03-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0006_rename_collection_oldcollection'),
        ('promotions', '0009_alter_promotion_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection_manager.theme')),
            ],
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('theme', 'promotion'), name='unique_collection'),
        ),
    ]
