# Generated by Django 5.0.6 on 2025-03-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0007_collection_collection_unique_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldcollection',
            options={'verbose_name': 'old collection', 'verbose_name_plural': 'old collections'},
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(upload_to='images/themes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
