# Generated by Django 5.0.6 on 2025-03-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0008_alter_oldcollection_options_alter_theme_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardprize',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_prizes', to='collection_manager.collection'),
        ),
        migrations.AlterField(
            model_name='standardprize',
            name='description',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='surpriseprize',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surprise_prizes', to='collection_manager.collection'),
        ),
        migrations.AlterField(
            model_name='surpriseprize',
            name='description',
            field=models.CharField(default='undefined', max_length=100),
        ),
    ]
