# Generated by Django 5.0.6 on 2025-03-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0009_alter_standardprize_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='collection_manager.collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='collection_manager.layout'),
        ),
    ]
