# Generated by Django 5.0.6 on 2025-03-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0010_layout_alter_coordinate_collection_collection_layout'),
        ('promotions', '0009_alter_promotion_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collection_manager.layout'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion'),
        ),
    ]
