# Generated by Django 5.0.6 on 2025-03-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0012_alter_collection_promotion'),
        ('promotions', '0009_alter_promotion_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='collection_manager.layout'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='promotions.promotion'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='collection_manager.theme'),
        ),
    ]
