# Generated by Django 5.0.6 on 2024-11-10 14:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_manager', '0001_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_manager.collection')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.BigIntegerField(default=0, verbose_name='ordinal_box')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='editions.edition')),
            ],
            options={
                'verbose_name_plural': 'boxes',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.BigIntegerField(default=0, verbose_name='pack_ordinal')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='editions.box')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(verbose_name='Number ordinal de sticker')),
                ('on_the_board', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to=settings.AUTH_USER_MODEL)),
                ('coordinate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='collection_manager.coordinate')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='editions.pack')),
            ],
        ),
    ]
