# Generated by Django 5.1.7 on 2025-03-11 12:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_manager.collection')),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.BigIntegerField(default=0, verbose_name='ordinal_box')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='editions.edition')),
            ],
            options={
                'verbose_name_plural': 'boxes',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.BigIntegerField(default=0, verbose_name='pack_ordinal')),
                ('is_open', models.BooleanField(default=False)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='editions.box')),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(verbose_name='Number ordinal de sticker')),
                ('on_the_board', models.BooleanField(default=False)),
                ('is_repeated', models.BooleanField(default=False)),
                ('is_rescued', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to=settings.AUTH_USER_MODEL)),
                ('coordinate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='collection_manager.coordinate')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='editions.pack')),
            ],
        ),
        migrations.CreateModel(
            name='StickerPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_date', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'No reclamado'), (2, 'Reclamado'), (3, 'En tránsito'), (4, 'Entregado')], default=1)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sticker_prize', to='collection_manager.surpriseprize')),
                ('sticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='editions.sticker')),
            ],
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['collection'], name='editions_ed_collect_bfa638_idx'),
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['circulation'], name='editions_ed_circula_acf220_idx'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['collector', 'is_open'], name='editions_pa_collect_4737d2_idx'),
        ),
    ]
