# Generated by Django 5.1.7 on 2025-03-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={},
        ),
    ]
