# Generated by Django 5.0.6 on 2025-01-17 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pack',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['collector', 'is_open'], name='editions_pa_collect_4737d2_idx'),
        ),
    ]
