# Generated by Django 5.0.6 on 2025-01-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_pack_collector_pack_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='is_repeated',
            field=models.BooleanField(default=False),
        ),
    ]
