# Generated by Django 5.0.6 on 2025-01-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0004_coordinate_image'),
        ('editions', '0003_sticker_is_repeated'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_date', models.DateTimeField(blank=True, null=True)),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_manager.surpriseprize')),
                ('sticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='editions.sticker')),
            ],
        ),
    ]
