# Generated by Django 5.0.6 on 2025-01-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0005_stickerprize_claimed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerprize',
            name='claimed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
