# Generated by Django 5.0.6 on 2025-02-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0006_alter_stickerprize_claimed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerprize',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'No reclamado'), (2, 'Reclamado'), (3, 'En tránsito'), (4, 'Entregado')], default=1),
        ),
    ]
