# Generated by Django 5.0.6 on 2025-02-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0007_stickerprize_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='is_rescued',
            field=models.BooleanField(default=False),
        ),
    ]
