# Generated by Django 5.0.6 on 2025-03-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0005_theme'),
        ('editions', '0008_sticker_is_rescued'),
        ('promotions', '0009_alter_promotion_start_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['promotion', 'collection'], name='editions_ed_promoti_bce6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['circulation'], name='editions_ed_circula_acf220_idx'),
        ),
    ]
