# Generated by Django 5.0.6 on 2025-03-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0010_layout_alter_coordinate_collection_collection_layout'),
        ('editions', '0009_edition_editions_ed_promoti_bce6b3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='edition',
            name='editions_ed_promoti_bce6b3_idx',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='promotion',
        ),
        migrations.AlterField(
            model_name='edition',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_manager.collection'),
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['collection'], name='editions_ed_collect_bfa638_idx'),
        ),
    ]
