# Generated by Django 5.0.6 on 2025-03-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0013_alter_collection_layout_alter_collection_promotion_and_more'),
        ('editions', '0010_remove_edition_editions_ed_promoti_bce6b3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='collection_manager.collection'),
            preserve_default=False,
        ),
    ]
