# Generated by Django 5.0.6 on 2025-03-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0011_box_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='edition',
        ),
    ]
