# Generated by Django 5.0.6 on 2025-03-06 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0012_remove_box_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='editions.edition'),
            preserve_default=False,
        ),
    ]
