# Generated by Django 5.0.6 on 2025-03-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0013_box_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='collection',
        ),
    ]
