# Generated by Django 5.0.6 on 2024-11-10 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pack_cost', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='costo unitario del sobre')),
                ('box', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.box')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.SmallIntegerField()),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='editions.edition')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='editions.pack')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='sales.sale')),
            ],
        ),
    ]
